version: '3'       
services:          
  db:
    image: mysql:5.7    
    environment:                  
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django-db
      MYSQL_USER: daiki
      MYSQL_PASSWORD: daiki0727
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
                                  
  web:
    build: .       
    command: python3 manage.py runserver 0.0.0.0:8000 
    volumes:                 
      - .:/echo
    ports:                   
      - "8000:8000"
      - "443:8000"
      - "80:8000"
    depends_on:               
      - db