version: '3'       
services:          
  db:
    image: mysql:5.7    
    environment:                  
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django-db
      MYSQL_USER: daiki
      MYSQL_PASSWORD: daiki0727
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
            - ./db/mysql_data:/var/lib/mysql
                                  
  web:
    build: .       
    command: python3 manage.py runserver 0.0.0.0:8000 
    volumes:                 
      - .:/echo
    ports:                   
      - "8000:8000"
    depends_on:               
      - db
  
  https-portal:
    image: steveltn/https-portal:latest
    ports:
      - 80:80
      - 443:443
    links:
      - web
    environment:
      DOMAINS: 'taikenki.info -> http://web:8000'
      STAGE: 'production'
      #FOECE_RENEW: 'true'
    volumes:
      - ./ssl_certs:/var/lib/https-portal

volumes:
  ssl_certs:
