# Generated by Django 3.1.7 on 2022-04-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_experiences_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiences',
            name='how_to_study_site',
            field=models.CharField(default='', max_length=100),
        ),
    ]
