# Generated by Django 3.1.7 on 2021-04-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_experiences_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiences',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
