# Generated by Django 3.1.7 on 2022-04-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0003_experiences_how_to_study_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiences',
            name='score',
            field=models.CharField(default='', max_length=50),
        ),
    ]
