# Generated by Django 3.1.7 on 2022-04-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0005_auto_20220421_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='how_to_study',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
