# Generated by Django 3.1.7 on 2022-04-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0006_auto_20220421_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiences',
            old_name='cram',
            new_name='予備校',
        ),
    ]
